# Generated by Django 4.1.6 on 2023-02-07 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abonne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(default=None, max_length=50)),
                ('nom', models.CharField(default=None, max_length=50)),
                ('prenom', models.CharField(default=None, max_length=50)),
                ('courriel', models.CharField(default=None, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Bibliotheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default=None, max_length=50)),
                ('ville', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.CharField(default=None, max_length=150)),
                ('titre', models.CharField(default=None, max_length=50)),
                ('editeur', models.CharField(default=None, max_length=50)),
                ('bibliotheque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1_tb.bibliotheque')),
            ],
        ),
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateEmprunt', models.DateTimeField()),
                ('dateRetour', models.DateTimeField()),
                ('abonne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1_tb.abonne')),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1_tb.livre')),
            ],
        ),
        migrations.AddField(
            model_name='abonne',
            name='bibliotheque',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1_tb.bibliotheque'),
        ),
    ]
